add workshop - robot emails and templating
hackclub/hackclub pull request #1313
Opened 2020-09-19 03:29 UTC by Rohan-Bansal

Hi! I'm Rohan, and I just created a new workshop on sending robot emails with easy substitution!

#### *1-2 minute video clip from your test club meeting showing what members built*

See it here: https://cloud-kjphlxr7m.vercel.app/robot_vid.mp4 (also on slack #workshop-skunkworks)

#### *Quick Description*

This workshop is a quick and relatively simple (20-25 minutes max) project utilizing Python's SMTP library. It allows the user to create, send, and modify emails at a much, much faster rate to many more people; by using Python's native string formatting, it's quite modular too!

#### *Easy to hack on for long periods of time after completion*

There are a __lot__ of things you can do with this after completion; extensions can keep you occupied for weeks. A few examples of further projects include: switchable SMTP servers, switchable message bodies during runtime, auto responders, and many more.

#### *Have instructive and compelling images, GIFs, and visuals*

As a terminal application, there isn't much in the way of visuals, but I included everything I could to make sure the workshop is clear and compelling.

#### *Use repl.it or a similar service that allows members to begin coding with one click*

All the main code and demos are on [repl.it](https://repl.it) as well as on GitHub.

#### *Link unknown concepts to external sources*

Every single unknown concept in the tutorial is linked on the spot.

#### *End with at least 3 demos of how the project can be expanded, with live links and code links for each demo*

I added three demos, some of which were enumerated above. All have descriptions, live code demos, and a home on GitHub.

2020-09-19 18:36 UTC, Rohan-Bansal commented
Please let me know if there's anything to change! I'd love the feedback.

2020-09-21 18:27 UTC, zachlatta commented
Awesome! I'm assigning @MatthewStanciu to be your reviewer on this :-).

2020-09-28 02:48 UTC, Rohan-Bansal commented
Hi! I understand there's a backlog, but I was wondering when I'd get an update. @MatthewStanciu ?

2020-10-08 02:31 UTC, Hugoyhu commented
Hi, please provide a slack handle and/or hack club you lead, thanks!

2020-10-08 02:58 UTC, Rohan-Bansal commented
@Hugoyhu I'm "solace" (Rohan Bansal) on Slack.

2020-10-08 03:08 UTC, Hugoyhu commented
Thank you!

On Oct 7, 2020, at 10:58 PM, Rohan Bansal <notifications@github.com<mailto:notifications@github.com>> wrote:



@Hugoyhu<https://github.com/Hugoyhu> I'm "solace" (Rohan Bansal) on Slack.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1313#issuecomment-705300240>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMD2RFBYCBOB2Z77VSDSJUTG3ANCNFSM4RSYNADQ>.

2020-10-09 19:33 UTC, MatthewStanciu requested changes
Thanks so much for submitting this! This looks like a super cool workshop.

Here’s a list of thoughts I had as I was going through the workshop:

* Instead of “head over to repl.it and create a new Python3 project”, I would just say “Head over to repl.it/languages/python3
* Include an image or gif demonstrating how to upload files
* “The contacts.txt file” line includes a typo “bu”
* The \<Your Name\> with the <> formatting may be confusing to some people. I would remove the angle brackets there
* The _Quick Note_ thing should all be one line in italics
* It may be worth including a .env setup step so that people aren’t putting the password to their google account in a public repl
* Does this workshop work for school google accounts? If you have a school google account that you can use to verify this, you definitely should, because if it doesn’t, many club members will likely be confused
* Love that a lot of the information that would take a while to explain is opt-in and links to pages with more info if people want to know 👍
* Maybe before the “Getting Contacts” section, I would include a screenshot of you repl so that people have some context of where each piece of code is and where we currently are in the workshop. (It seems like a small thing but it’s really easy for people, especially beginners, to lose track of what’s going on in a workshop)
* A little unclear to me how much Python people are supposed to understand. Is this a beginner workshop? Intermediate? If there are any concepts people are supposed to understand before they get started, you should specify at the beginning.
* A lot of the code you write is presented in large chunks with little explanation (though the “important elements” part is good). You said not to copy but the more code is presented in large chunks the more likely people are to copy
* I got a little lost at first glance at the bottom of the “reading the message” section. 2 of the 3 code blocks starting after “Let’s go over:” are calling back to the previous chunk of code and explaining bits of it, while the third one is code that you’re supposed to add at the bottom of the file. Instead of “Test out both of these functions, here’s how to do it:” I would instead say “Let’s test both of these functions! At the end of your `main.py` file, add:”
* “After doing this, go ahead an remove the print statements” line is confusing to me. After doing what? Was I supposed to have run the file after I added those lines of code? This should be clearer
* Love the examples on how to expand the workshop at the end

2020-10-10 00:44 UTC, Rohan-Bansal commented
Hi @MatthewStanciu ! I just tweaked the workshop to include all of your suggestions. About the school-email thing, it's definitely possible! I built/tested this workshop with my school account, and was able to follow all the steps.

Could you look over my changes?

2020-10-10 02:42 UTC, lachlanjc commented on workshops/robot_emails/README.md
> +*After working on this project, it is recommended to turn the less secure apps lever back to it's off position.*
```suggestion
*After working on this project, it is recommended to turn the less secure apps lever back to its off position.*
```

2020-10-12 15:34 UTC, MatthewStanciu commented
Wow, this is really good now! I think it’s basically ready to merge. I’ll do one more deep dive and let you know.

2020-10-12 17:17 UTC, MatthewStanciu approved these changes

2020-10-12 18:51 UTC, lachlanjc approved these changes

2020-10-12 18:51 UTC, merged