README.md
hackclub/hackclub pull request #1332
Opened 2020-09-25 00:30 UTC by maddieWillett-boop

name: 'Basic Data Visualizations with Python'
description: 'Create basic graphs and data visualizations using Python!'
author: '@maddieWillett-boop'

2020-09-25 03:12 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +**![](https://lh5.googleusercontent.com/kf8WU2xC639Ogql75pwjVJFsHLkL1Jc39FNmU985vWokqKD7IsnbpUYYgYTn1ke_RzrsH4E3zELEMEAGhdUFwghXyNX75iWV8kwH_v4ADJETTzO-5IsHcijdSwtwf3gbBbC994tc0FA)**
could you host this on Hack Club's CDN?

2020-09-25 03:13 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +#
```suggestion
```

2020-09-25 03:13 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +#
```suggestion

```

I dont think we need these

2020-09-25 03:13 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +
could we delete

2020-09-25 03:14 UTC, sampoder commented
hey @maddieWillett-boop could you make the Markdown a bit cleaner with smth like: https://www.markdownbeautifier.com/#

2020-09-25 03:15 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +**![](https://lh5.googleusercontent.com/kf8WU2xC639Ogql75pwjVJFsHLkL1Jc39FNmU985vWokqKD7IsnbpUYYgYTn1ke_RzrsH4E3zELEMEAGhdUFwghXyNX75iWV8kwH_v4ADJETTzO-5IsHcijdSwtwf3gbBbC994tc0FA)**
oh also add alt text

2020-09-25 11:49 UTC, maddieWillett-boop commented on workshops/python and data visualizations/README.md
> +
which part?

2020-09-25 11:58 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +
the extra new lines

2020-09-25 12:08 UTC, maddieWillett-boop commented on workshops/python and data visualizations/README.md
> +
@samepoder done

2020-09-25 12:10 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +
cool! thanks, same (jk)

2020-09-25 12:14 UTC, sampoder commented
coz my notes above are simply formatting im going to do a content review rn

2020-09-25 12:37 UTC, sampoder reviewed
Did a content review, uploading soon @ https://youtu.be/6deLs_fFZ2s

Let me know if you've got any questions :D

2020-09-26 03:11 UTC, maddieWillett-boop commented
@sampoder Made a bunch of edits! Hopefully made it clearer, added some code descriptions, etc. Let me know what you think! :)

Also... [Chicken Little](https://en.wikipedia.org/wiki/Chicken_Little_(2005_film)) is a movie haha you made me laugh so hard w/ ur narrations of things.

2020-09-26 04:27 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +![Winnie the Poo dancing!](https://i.pinimg.com/originals/50/5a/0e/505a0e4591fc8052631bed84ac0de1ee.gif)
lets move this below the header

2020-09-26 04:27 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +<h1> Create basic graphs and data visualizations with python! </h1>
```suggestion
# Create basic graphs and data visualizations with python!
```

2020-09-26 04:28 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +You after you make your first data visualization^
what about a stonks meme to mix it up?

2020-09-26 04:28 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +<p> Follow along with this workshop to gain some data science skills! You will use python to create basic graphs and visualizations with real data. You can hand draw a graph anytime you want, but why
```suggestion

Follow along with this workshop to gain some data science skills! You will use python to create basic graphs and visualizations with real data. You can hand draw a graph anytime you want, but why not learn how to code one! You will learn about matplotlib, pandas, and numpy, so you can create any graph or vizualizaiton you dream of!
```

2020-09-26 04:28 UTC, sampoder commented on workshops/python and data visualizations/README.md
> +</p>
```suggestion

```

2020-09-26 04:42 UTC, sampoder commented
in no way is this complete but: https://github.com/maddieWillett-boop/hackclub/pull/1 has some formatting changes that could be added

2020-09-26 15:35 UTC, maddieWillett-boop commented
@sampoder made some more formatting changes, do you spot anything else that needs to be fixed? When you say "in no way is this complete" what should I work on to make it closer to completion?

2020-09-26 15:36 UTC, sampoder commented
Wait whend I say that

2020-09-26 15:36 UTC, sampoder commented
I doubt I meant it in that way.... lol

2020-09-26 16:42 UTC, maddieWillett-boop commented
@sampoder Oh I did not mean that in a bad way haha :) , I just was wondering if there is anything else?

2020-09-27 01:57 UTC, sampoder commented
main thing rn is we need the demos

2020-09-27 02:11 UTC, maddieWillett-boop commented
From the club meeting? I uploaded a video to the workshop-skunk works channel. But let me try again...

2020-09-27 02:11 UTC, maddieWillett-boop commented
can you see it now?

2020-09-27 03:00 UTC, sampoder commented
I mean the 3 examples for building on top of the workshop

2020-09-27 12:51 UTC, maddieWillett-boop commented
ok if you scroll down to the very bottom of the workshop there is a "add on" and "learn more" section that have 3+ links and ideas in each part.

2020-09-27 13:13 UTC, sampoder commented
Yep, so with those I think we want them to show progression from this specific workshop, correct me if I'm wrong they seem to be unrelated

2020-09-27 13:23 UTC, maddieWillett-boop commented
Ok, so should I show some examples that I made with the add on resources? 

I would say they are related to the workshop because with those resources all you have to do is add a couple lines to the code that we made above. One of the resources teaches you how to import csv files and it will plot points from the real data into graph instead of making up plotting points. Also, looking up to use google trends and incorporate that into a graph,  another source that has code and teaches you how to create different graphs (how to add colors, shapes, dot plots, pie charts, etc.) And a link to another “workshop” that uses the same IDE and code we learned to make data visualizations with Covid-19 Data. Then in the learn more section there are links that teach you more about the libraries we used and all the things you can create amongst them. For instance, matplotlib, pandas, and numpy. So I think that they all relate back to the workshop, and encourage them to add more/personalize the basic graphs we made in the workshop.

2020-09-27 13:27 UTC, maddieWillett-boop commented
I think it shows progression because you can really build upon the simple graphs and plots we made with the resources, it brings it up to another level. What the goal of the workshop was to teach the basics and the add ons use the basics you learn as a foundation and add more to make it more complicated and intersting.  For instance, in my club during the time were they were adding on to what they made one member imported google trends into his project and made a graph that used real google trend data to see the correlation of tik tok and popularity over time, another one personalized it to show comparisons from his life in the United States and Inda, and another learned how to import a csv file from the resources and made a data visualization that showed the population of the United States over time.

2020-09-27 13:30 UTC, maddieWillett-boop commented
But maybe I am misinterpreting it, let me know what you think...

2020-09-27 13:34 UTC, sampoder commented
k, I don't think I phrased it correctly. The demos (based on all the other workshops) need to be directly building on top of the project, view example: https://workshops.hackclub.com/sound_galaxy/#hacking

2020-09-27 13:34 UTC, sampoder commented
now I've asked Zach to clarify if im getting smth wrong (just started helping out with workshop review)

2020-09-27 13:35 UTC, sampoder commented
ohhh also when I said in no way is this complete I was referring to **my** pr, not this pr.... could you merge that pr?

2020-09-27 13:35 UTC, sampoder commented
https://github.com/maddieWillett-boop/hackclub/pull/1

2020-09-27 13:42 UTC, maddieWillett-boop commented
Ohhh haha I see now okay I will make those edits @sampoder, also I still think that the demos are directly building on top of the project lol maybe my edit is that it needs to be that I show the exact code as well (kind of like how I did w/ examples in the workshop, and how it is in the sound galaxy workshop)?

2020-09-27 14:04 UTC, sampoder commented
yep, how it is in the sound galaxy one, thank you!

2020-09-27 16:33 UTC, maddieWillett-boop commented
@sampoder fixed it, now there are examples :)

2020-09-27 23:15 UTC, maddieWillett-boop commented
Anything else that should be edited?

2020-09-28 00:21 UTC, sampoder commented
will review in a bit

2020-09-29 01:02 UTC, maddieWillett-boop commented
ok sounds good

2020-10-01 11:45 UTC, maddieWillett-boop commented
@sampoder do you think it is ready for the next steps?

2020-10-01 12:03 UTC, sampoder commented
I kinda want a second person's perspective, @faisalsayed10 would you mind taking a look?

2020-10-01 12:26 UTC, faisalsayed10 commented
Yep, taking a look into it rn.

2020-10-01 12:39 UTC, faisalsayed10 reviewed
These are the very few changes and overall this workshop is great! :+1:

2020-10-01 12:39 UTC, faisalsayed10 commented on workshops/python and data visualizations/README.md
> +Get started by going to [Try Jupyter](https://jupyter.org/try). When you get to the website you will see something like this...
```suggestion
Get started by going to [Jupyter](https://jupyter.org/try). When you get to the website you will see something like this...
```

2020-10-01 12:39 UTC, faisalsayed10 commented on workshops/python and data visualizations/README.md
> +Get started by going to [Try Jupyter](https://jupyter.org/try). When you get to the website you will see something like this...
"Get started by going to Jupyter" looks more good in my opinion

2020-10-01 12:39 UTC, faisalsayed10 commented on workshops/python and data visualizations/README.md
> +*Can you tell I have a strange fascination with random things dancing hehe*
a full stop or an exclamation at the end here?

2020-10-01 12:39 UTC, faisalsayed10 commented on workshops/python and data visualizations/README.md
> +*Make sure libraries are uploaded, look back @ Step Two if needed*
```suggestion
*Make sure libraries are uploaded, look back @ Step Two if needed*.
```

2020-10-02 01:04 UTC, maddieWillett-boop commented
Awesome, thank you @faisalsayed10!

2020-10-02 01:05 UTC, maddieWillett-boop commented
Made those updates, what should I do next?

2020-10-02 02:03 UTC, faisalsayed10 commented
@sampoder we can ask for the final review now?

2020-10-03 16:07 UTC, maddieWillett-boop commented
@sampoder @faisalsayed10 sounds good to me, just lmk what you want me to edit :)

2020-10-07 01:43 UTC, maddieWillett-boop commented
@sampoder do you have an idea of what I should do next (editing wise, etc.) is it ready for the final review?

2020-10-07 02:03 UTC, sampoder commented
yep, waiting for final review (cc: @zachlatta)

2020-10-07 03:01 UTC, zachlatta commented
Yes, thanks. This is next in line for my review.

On Oct 6, 2020, at 22:03, Sam Poder <notifications@github.com> wrote:

﻿

yep, waiting for final review (cc: @zachlatta <https://github.com/zachlatta>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hackclub/hackclub/pull/1332#issuecomment-704648122>, or
unsubscribe
<https://github.com/notifications/unsubscribe-auth/AAHSH6D4UMYM3SUGY7ROCZ3SJPD7VANCNFSM4RY5OSNQ>
.

2020-10-17 04:34 UTC, bezlin6mechminerz commented on workshops/python and data visualizations/README.md
> +*Follow along with this workshop to gain some data science skills! You will use python to create basic graphs and visualizations with real data. You can hand draw a graph anytime you want, but why no
```suggestion
*Follow along with this workshop to gain some data science skills! You will use python to create basic graphs and visualizations with real data. You can hand draw a graph anytime you want, but why not learn how to code one! You will learn about matplotlib, pandas, and numpy, so you can create any graph or visualization you dream of!*
```

2020-10-21 04:25 UTC, lachlanjc requested changes
This is an awesome start!!! I’ve made a bunch of specific suggestions & requests here, the ones at the beginning which we’ll definitely need in order to to merge. I think my primary piece of feedback is that you should focus it at the beginning a little more on a specific end product: we’re going to do exactly x using Python & Jupyter, with a screenshot of what you’ll have made by the end. We have a lot of fun GIFs & graphics throughout, but I’d replace or add to a few of those with screenshots of the project at each stage, so it’s clear if folks are on track or not. I think the last section also needs more fleshing out/context, as in: here’s how to share your resulting project, then here’s some suggestions for where to take your project, not just the links to documentation/resources (which are awesome). This is 2/3 of the way there, & I think with those beginning edits & a bit of clarification at the beginning & end we’ll push it to completion. Super appreciate your submission!

EDIT: Going to close this for now since we’re clearing out the PRs but if you’re interested, once you’ve focused the article on a specific project, go ahead & make a new PR & we’re happy to review. Thanks!

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +![Stonks](https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fentries%2Ficons%2Ffacebook%2F000%2F029%2F959%2FScreen_Shot_2019-06
Please re-host on the #cdn channel :)

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +
Please rename the folder to `python_dataviz` or something—remove the spaces though

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +You after you make your first data visualization^
Please add the metadata as requested in the bounty guidelines to the start of the file

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +*Follow along with this workshop to gain some data science skills! You will use python to create basic graphs and visualizations with real data. You can hand draw a graph anytime you want, but why no
The start of your workshop should lay out a specific thing you’re going to make, with a link &/or screenshot of the live demo, as well as the source code. Even if folks deviate from the workshop (which we hope they will) to take it in their own direction, they should be able to follow it with no changes & get exactly what you did.

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +``` python
```suggestion
```python
```

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +**![](https://lh6.googleusercontent.com/ANl3lVAPXZfLS8CDBbqIv3Pu8zYpzp5kqXoqBwa4RsDg0g-B0g3x_YnssB2ddfbSh1chvWTnWkvJKFZpuxOcfcQ3aT1vbxxoA3NX2LCY1KnIUXtfNIjeFuMAVW0vQ1RvhgijbcilX9c)**
Add alt text

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +**![](https://cloud-3r2clygpe.vercel.app/0image_from_ios.jpg)**
alt text

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +### Okay now lets get back to it...
```suggestion
### Okay, now let’s get back to it...
```

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +\*Make sure your libraries are uploaded!
```suggestion
```

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +Here is a hint
```suggestion
Here’s a hint:
```

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +`fig,ax= plt.subplots()`
```suggestion
*Still stuck? Where the underscores are, replace with `fig,ax= plt.subplots()`.*
```

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +**![](https://lh3.googleusercontent.com/x7NafZjPviM76xz95YQKc4L8kW4zC3B5_zp4wE7Qv4FKWVX-6ZoB_4qtT4WbA1er9soAcMHZeBNgJgLMttFnr1hiXOkWxLQpBXI3uQQyRd7wOElTYLWZtczqgTvmWvmdOEzmnqMTECg)**
alt text here & below

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +```
You should have screenshots throughout of what your graph should look like if you’ve followed the code correctly

2020-10-21 04:25 UTC, lachlanjc commented on workshops/python and data visualizations/README.md
> +#
```suggestion
```

2020-10-21 05:31 UTC, closed without merging

2020-10-21 05:46 UTC, lachlanjc commented
(Pulling this comment down so it’s easier to find.) Closing this for now since we’re clearing out the PRs here, but if you’re interested, once you’ve focused the article on a specific project, go ahead & make a new PR & we’d be super happy to review. Thanks a bunch!

2020-10-22 00:26 UTC, maddieWillett-boop commented
@lachlanjc submitted new pull request :)