Create README.md
hackclub/hackclub pull request #1361
Opened 2020-10-09 05:47 UTC by bezlin6mechminerz

Link to the tested workshop:- https://hackclub.slack.com/files/UJMRP65K9/F01BCC0UJ2Z/tts.mp4
This is a workshop to convert text to speech using python.

2020-10-10 03:04 UTC, sampoder requested changes
Could we extend this workshop out? It's quite short.

Also my most recent review on #1316 is relevant.

2020-10-10 03:44 UTC, bezlin6mechminerz commented
Ok

2020-10-10 05:04 UTC, bezlin6mechminerz commented
I will do that soon

2020-10-12 16:14 UTC, lachlanjc requested changes
I’d love to have this workshop, but currently this is just not complete enough & doesn’t create a compelling enough final product. Workshops should be focused on making an end product beginners will be interested in, not on the technology they use to achieve this. This workshop is just about the tech, & barely mentions the usecases at the end. You could solve this by making it a website with an input that generates the file on the backend & plays it, or making a barebones Siri-like thing that responds to you using this technology in some way, etc, but just using the module to generate the file inside code isn’t enough. Additionally, this workshop is missing alt text on images, there are many grammar/punctuation errors (I flagged a few but they are throughout), & the instructions for repl.it users are a bit confusing. I’m closing for now, but feel free to re-open if you’d like to address these for the bounty. Thanks so much.

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +View the [final code](https://repl.it/@bezlin/tts#main.py) .
```suggestion
View the [final code](https://repl.it/@bezlin/tts#main.py)
```

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +<img width="1440" alt="Screenshot 2020-09-19 at 12 43 28 PM" src="https://cloud-amkazzxks.vercel.app/93708256-6181ad80-fb52-11ea-9c6b-f1d7534c5520.png">
Missing descriptive alt text, & use Markdown syntax for image

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +## Lets code
Punctuation

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +For getting this module you need to install the gtts package. Don't worry if you are using repl.it.In repl.it it will be automatically installed when you run the code.
You should assume folks are using replit here. The grammar is off here/on the next line

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +`pip install gTTS`
Unclear if you need to do this on replit

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +Now you know how to convert. Try it with other languages and have fun. Try to make a help part in your codes which says the whole help as voice .its pretty cool right?. Elaborate on it and bring more
Punctuation/grammar off here

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +![ezgif com-gif-to-mp4](https://cloud-5m2nwfs8r.vercel.app/ezgif.com-video-to-gif-4.gif)
Alt text on this & above

2020-10-12 16:14 UTC, lachlanjc commented on workshops/Convert text to speech/README.md
> +So before the above code, the text is converted to the voice but we need to save it right? To save it, the gtts module itself has a save function. the variable we converted to voice .save that's it A
“Hope you got it”—it’s really important that we use a welcoming tone for beginners

2020-10-12 16:14 UTC, closed without merging

2020-10-12 16:48 UTC, bezlin6mechminerz commented
ok