Create README.md
hackclub/hackclub pull request #1365
Opened 2020-10-10 04:50 UTC by bezlin6mechminerz

Hackclub :- sacred hearts computer club

2020-10-10 04:52 UTC, faisalsayed10 commented
Hi @bezlin6mechminerz! by the way, are you a member or a leader of your club?

2020-10-10 05:02 UTC, bezlin6mechminerz commented
Leader

2020-10-10 05:51 UTC, bezlin6mechminerz commented
Hackclub is for real @zachlatta visited our school

2020-10-10 08:15 UTC, sampoder commented
Not all of the requested changes were made, please only reopen the PR when all requested changes were made.

2020-10-10 13:12 UTC, sampoder commented
@lachlanjc can you close this? @bezlin6mechminerz refer to my comment on #1316 and make sure all changes are made.

2020-10-10 14:31 UTC, bezlin6mechminerz commented
wait!

2020-10-10 14:32 UTC, bezlin6mechminerz commented
I have been spending all this time and fixed the grammar and phrases I will be updating it soon

2020-10-11 09:19 UTC, bezlin6mechminerz commented
I have made all the changes and i think its almost ready.

2020-10-12 15:32 UTC, lachlanjc requested changes
Thanks for the contribution, Bezlin! While I really like the idea of this workshop, the phrasing, grammar, & punctuation need some significant editing. I left a few comments here but there’s a lot more. Maybe you could go through this workshop with a friend for editing? Since perfect grammar/punctuation are a requirement for our workshop bounties, I unfortunately am closing this for now, but if you can get that fixed up we’d love to have your workshop.

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +If you don't understand it, just go to the live demo and see the button workflow [here](https://repl.it/@bezlin/graphics#main.py).
```suggestion
If you don't understand, just go to the live demo and see the button workflow [here](https://repl.it/@bezlin/graphics#main.py).
```

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +window.config means we are configuring our window and setting up its bg which is short for background. Now let's display the Quotes Hub in the window we made. For that we use the Label function.
```suggestion
I used black, but you can also specify the color as a hex code or RGB value.
`window.config` means we are configuring our window and setting up its bg which is short for background. Now let's display the Quotes Hub in the window we made. For that we use the Label function.
```

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +The Label function is used to display text on the window. The Label function takes parameters such as font,text,background color(bg) ,font color(fg) .The first parameter you should give is the name o
Spaces missing/mistakes here

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +The Tkinter library consists of A Button function which is used to display a button on the window. The button function  takes many parameters such as text,bg,fg,width,height etc... The first paramete
Spaces missing/mistakes here

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +In the output, an error will be shown,that the function clicked is not declared. So let us make the button work. You need to put this code above the window declaration ,only then will it work.
Awkward grammar/punctuation mistakes here

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +Its simple, you just have to go through the functions and workflow.
```suggestion
It’s simple, you just have to go through the functions and workflow.
```

2020-10-12 15:32 UTC, lachlanjc commented on workshops/Tkinter Workshop/README.md
> +Lastly, don't get give up.
Grammar

2020-10-12 15:33 UTC, closed without merging

2020-10-12 16:49 UTC, bezlin6mechminerz commented
OK

2020-10-12 16:49 UTC, bezlin6mechminerz commented
I will make changes and come back again

2020-10-12 17:04 UTC, sampoder commented
thanks Bezlin!