Weather App (Workshop Bounty)
hackclub/hackclub pull request #1366
Opened 2020-10-10 12:18 UTC by gautamjajoo

Added a new workshop on the topic <b> Weather App</b>. This workshop primarily focusses on how APIs work.

P.S: I am a member of the Slack community but not a leader of any club.

2020-10-10 12:26 UTC, faisalsayed10 commented
Hi, have you read the workshop bounty guidelines? We need the demo video of your workshop and also you need to be an *active* member of slack if you are not a club leader.
Here are the guidelines: https://hackclub.com/workshop-bounty/

2020-10-10 12:28 UTC, gautamjajoo commented
@faisalsayed10 Yes, I know that the demo video is required. Just wanted to know where should I upload? Uploading in GitHub description of the issue would work?

2020-10-10 12:29 UTC, faisalsayed10 commented
You need to upload it in the channel #workshop-skunkworks and paste a link to it in the description.

2020-10-10 12:30 UTC, gautamjajoo commented
@faisalsayed10 Ok. Thank you for the information! :)

2020-10-10 12:58 UTC, sampoder commented
> Hi, have you read the workshop bounty guidelines? We need the demo video of your workshop and also you need to be an **active** member of slack if you are not a club leader.
> Here are the guidelines: https://hackclub.com/workshop-bounty/

@gautamjajoo this is quite important

2020-10-10 13:24 UTC, gautamjajoo commented
> > Hi, have you read the workshop bounty guidelines? We need the demo video of your workshop and also you need to be an **active** member of slack if you are not a club leader.
> > Here are the guidelines: https://hackclub.com/workshop-bounty/
> 
> @gautamjajoo this is quite important

I have read the guidelines. Also, I have updated the description where I was making the app with my fellow mates.

2020-10-10 13:30 UTC, sampoder commented
I'm trying to point out that you need to be a leader or an active member of Slack

2020-10-10 13:34 UTC, Hugoyhu commented
Please provide a slack handle, you _must_ be an **_active_** slack member in order to submit a workshop.

2020-10-10 13:38 UTC, sampoder commented
Yes, Hugo. Thanks for repeating what I said :D

2020-10-10 13:39 UTC, gautamjajoo commented
@sampoder Got to know a bit late about the club, but surely would love to be active and help fellow coders on Slack!

2020-10-10 13:39 UTC, Hugoyhu commented
:|
Well yes but I also requested a slack handle

On Oct 10, 2020, at 9:38 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



Yes, Hugo. Thanks for repeating what I said :D

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706550715>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMGEDXZPRWCSYHKF66LSKBPVRANCNFSM4SLA6AJA>.

2020-10-10 13:39 UTC, Hugoyhu commented
Please provide a slack handle.

On Oct 10, 2020, at 9:39 AM, Gautam Jajoo <notifications@github.com<mailto:notifications@github.com>> wrote:



@sampoder<https://github.com/sampoder> Got to know a bit late about the club, but surely would love to be active and help fellow coders on Slack!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706550806>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMDRD7CDPSW5ZJBF75TSKBPYDANCNFSM4SLA6AJA>.

2020-10-10 13:41 UTC, sampoder commented
I'm not sure about HQ's guidelines are exactly on this (cc: @lachlanjc)

@Hugoyhu I got it, dw.

2020-10-10 13:43 UTC, Hugoyhu commented
Please provide a slack handle.
Do you not understand what this means?

This means, please provide the handle of your slack account.

On Oct 10, 2020, at 9:41 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm not sure about HQ's guidelines are exactly on this (cc: @lachlanjc<https://github.com/lachlanjc>)

@Hugoyhu<https://github.com/Hugoyhu> I got it, dw.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706551047>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMAOELTQRB3LBTUDA3TSKBP77ANCNFSM4SLA6AJA>.

2020-10-10 13:43 UTC, sampoder commented
Hugo, they have.

2020-10-10 13:43 UTC, sampoder commented
> @sampoder Got to know a bit late about the club, but surely would love to be active and help fellow coders on Slack!
> If there seems to be a problem, will close the PR :)
> Slack handle: @Gautam

cc: @Hugoyhu, please check your glasses Hugo.

2020-10-10 13:45 UTC, Hugoyhu commented
I don’t read thru all threads thanks for the handle.

You aren’t an active slack member-

If I am correct, your profile is default orange, you have 12 messages….



On Oct 10, 2020, at 9:44 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



@sampoder<https://github.com/sampoder> Got to know a bit late about the club, but surely would love to be active and help fellow coders on Slack!
If there seems to be a problem, will close the PR :)
Slack handle: @Gautam<https://github.com/Gautam>

cc: @Hugoyhu<https://github.com/Hugoyhu>, please check your glasses Hugo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706551358>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMDMZUGEWEQ3XQCONADSKBQKFANCNFSM4SLA6AJA>.

2020-10-10 13:46 UTC, sampoder commented
Yep, Hugo. We know. I asked for Lachlan's views to get HQ's policy on this.

2020-10-10 13:47 UTC, sampoder commented
Sorry @gautamjajoo seems there's been some miscommunication here. My apologies for all of this.

2020-10-10 13:50 UTC, Hugoyhu commented
As a matter of fact, I recall 3 or so PR’s, as far as I saw, being closed due to lack of hack club leader or activeness.

I will dig them out.

On Oct 10, 2020, at 9:47 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



Yep, Hugo. We know. I asked for Lachlan's views to get HQ's policy on this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706551696>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMDXLLSETC54BALIOXLSKBQVLANCNFSM4SLA6AJA>.

2020-10-10 13:53 UTC, sampoder commented
Hugo, let's both step back from this. I think it's better that we get the policy direct from HQ.

2020-10-10 13:56 UTC, Hugoyhu commented
I’ll stand by for HQ intervention.

On Oct 10, 2020, at 9:53 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



Hugo, let's both step back from this. I think it's better that we get the policy direct from HQ.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706552569>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMBONNTTD35SHZM264TSKBROZANCNFSM4SLA6AJA>.

2020-10-11 09:05 UTC, gautamjajoo commented
@lachlanjc Any update on this matter?

2020-10-11 14:08 UTC, Hugoyhu commented
Hi Gautum- I think there’s around… 3 or so people doing reviews, and each review process is very long… I understand that it’s annoying when results don’t come out for some time(I usually get pretty annoyed)… maybe give it a week or two then ask again if there are any updates? I’m not on the review team so I cannot give a timeline, unfortunately...

On Oct 11, 2020, at 5:05 AM, Gautam Jajoo <notifications@github.com<mailto:notifications@github.com>> wrote:



@lachlanjc<https://github.com/lachlanjc> Any update on this matter?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706673844>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDME3C7T7MHZKAK6NL3LSKFYPFANCNFSM4SLA6AJA>.

2020-10-11 15:17 UTC, gautamjajoo commented
@Hugoyhu I was not talking about the review rather I was asking about the guidelines. 
I have also been reviewing pull requests from some time and I know how difficult it is to review the PRs. Also that's why I deleted that comment just after I posted.

2020-10-11 15:19 UTC, Hugoyhu commented
I’m sorry, I misunderstood your comment.

My view is that if you’re not an active slack member or a hack club leader, you’re not eligible, as shown in the guidelines, but we are still waiting for HQ clarification.

On Oct 11, 2020, at 11:17 AM, Gautam Jajoo <notifications@github.com<mailto:notifications@github.com>> wrote:



@Hugoyhu<https://github.com/Hugoyhu> I was not talking about the review rather I was asking about the guidelines.
I have also been reviewing pull requests from some time and I know how difficult it is to review the PRs. Also that's why I deleted that comment just after I posted.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706720185>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMASEWTNA6KRNIVSD7TSKHD7XANCNFSM4SLA6AJA>.

2020-10-11 16:23 UTC, sampoder commented
GitHub really needs to get better and removing all that stuff from the bottom of the email :joy:

2020-10-11 16:35 UTC, Hugoyhu commented
Yes they do.

And,

Sam really needs to get better and sleep before midnight. 😂

On Oct 11, 2020, at 12:24 PM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



GitHub really needs to get better and removing all that stuff from the bottom of the email 😂

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hackclub/hackclub/pull/1366#issuecomment-706729586>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQOQDMBOQOH33YMSN5QZPB3SKHL2BANCNFSM4SLA6AJA>.

2020-10-12 15:47 UTC, lachlanjc requested changes
Hey, I love this idea! Unfortunately it does not meet all our guidelines

1. Can you add syntax highlighting to the code blocks?
2. The grammar/phrasing/punctuation needs significant editing—I left a few comments, but there’s a lot more spots. Grammar & punctuation must be perfect for our bounty.
3. The instructions aren’t clear enough in a number of areas; setting up an API account, for example. They could use more screenshots as well.
4. You need to link to demos at the end that take the project in a different direction/make creative hacks.
5. Your submission must be accompanied by a video clip from you running this workshop with friends or in your club.

I’m unfortunately closing this for now as it doesn’t meet all the requirements, but feel free to re-submit when you think it does. Thanks for your contribution—we really appreciate it.

2020-10-12 15:47 UTC, lachlanjc commented on workshops/weather_app/README.md
> +Making `position:relative` will cause it to be adjusted away from its normal position. Know more about
That’s not really how position works here—it’s changing how elements inside it are positioned, namely the psuedoelement. Also, grammar of second sentence is off

2020-10-12 15:47 UTC, lachlanjc commented on workshops/weather_app/README.md
> +For this project we would be using a weather API which is given by [OpenWeather](https://openweathermap.org/api). Firstly we have to read the docs
Add a quick explanation of what an API is/how it works

2020-10-12 15:47 UTC, lachlanjc commented on workshops/weather_app/README.md
> +TO start with, you will have to create an account on OpenWeather to generate an API key for yourself. After you have registered head over to get the
Add screenshots of how to do this

2020-10-12 15:47 UTC, lachlanjc commented on workshops/weather_app/README.md
> +![app](https://cloud-g1zuwwz9o.vercel.app/0app.gif)
Need more descriptive alt text

2020-10-12 15:47 UTC, lachlanjc commented on workshops/weather_app/README.md
> +Last but not the least, be as creative and dynamic as possible. This is only the start and I am sure after this workshop you would definitely create
You need to link to your or other hackers’ demos of doing something fun/different with the project—see guidelines

2020-10-12 15:47 UTC, closed without merging

2020-10-12 16:28 UTC, gautamjajoo commented
@lachlanjc Thank you for the feedback. I have uploaded a video where I am explaining the project to my fellow mates.
Also, If the mentioned points are rectified will it be considered for evaluation? Because there was some confusion on eligibility of submitting a PR!

2020-10-12 20:39 UTC, MatthewStanciu commented
@gautamjajoo Don’t worry about Hugo’s comments, you’re eligible to submit a workshop! Feel free to resubmit this workshop when you believe you’ve met all of the guidelines :)