React Random Quotes (Workshop Bounty)
hackclub/hackclub pull request #1417
Opened 2020-11-07 15:55 UTC by faisalsayed10

Follows all the guidelines and here's the demo link! : https://hackclub.slack.com/archives/C01A9V5LPD0/p1604764538019200

:)

2020-11-10 21:54 UTC, MatthewStanciu requested changes
Yay, nice work! Can you just make these four changes and ping me on Slack once you've made them?

2020-11-10 21:54 UTC, MatthewStanciu commented on workshops/quotes_generator/README.md
> +import React, { useState } from "react"; //<-- Import useState
Wait, where should this code go? App.js? Because this is very different from the code that was previously in App.js. Clarify here

2020-11-10 21:54 UTC, MatthewStanciu commented on workshops/quotes_generator/README.md
> +const randomNo = () => Math.floor(Math.random() * data.length) + 1;
Can you give a little bit more context for where this code should go? Could just be in the form of something like

```js
export default function App() {
 // code from earlier workshop
}

const randomNo = () => Math.floor(Math.random() * data.length) + 1;
```

2020-11-10 21:54 UTC, MatthewStanciu commented on workshops/quotes_generator/README.md
> +Make sure you create an account on codesandbox.io to save this wonderful piece of creation or you'll loose it 😧.
lose*

2020-11-10 21:54 UTC, MatthewStanciu commented on workshops/quotes_generator/README.md
> +Check out what other Hack Clubber built!
Hack Clubbers*

2020-11-11 01:31 UTC, faisalsayed10 commented
Oops, fixing them rn.

2020-11-11 17:15 UTC, MatthewStanciu commented
whoops i meant "add img" lol ^

2020-11-11 17:19 UTC, merged