Patch 5
hackclub/hackclub pull request #1439
Opened 2020-11-14 14:14 UTC by YashKalbande

Hello @MatthewStanciu, I have completed all the requested changes in workshop. Please review it.

2020-11-16 16:23 UTC, shreyfirst commented
I helped out here with clarity and language.

2020-11-30 19:29 UTC, MatthewStanciu requested changes
Great work! Left a few comments that identify a few changes that need to be made, but I think this is basically ready to merge 🚀

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +description: 'Simple Pac-man game using python'
Python*

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +* **NOTE:** If you ever get lost, feel free to open the Repl above and see where the code is being placed. All the code explained in this workshop is in order of first line to last line :) - Happy ha
Remove the dash before "Happy hacking"

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +We're going to be coding this using a principle called [modular programming](https://en.wikipedia.org/wiki/Modular_programming). This means we're going to be writing different functions that we will
Instead of "For example, this is how I will write a function" try "Here's an example function"

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +	total = parameter1 + parameter 2
weird intention here. also shouldn't it be `def functionName`? or am I misunderstanding?

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +Now, whenever I call `functionName`, I will get the sum of it's two parameters. You can call a function by just filling in the parameters:
its not it's

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +print(sum) //prints 11
incorrect comment syntax, in python i think it's `#`

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +If at any time you want to test the functions we create, just use the example above as a reference and write it in a new line.
Not sure what this sentence is saying. Clarify maybe, or maybe just remove it altogether

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +* Validity - ensuring that our Pac-Man can't do anything suspicious and run through the bricks!
Inconsistent capitalization. Is it Pac-man or Pac-Man? Whichever one it is, that should be the one that used throughout the entire workshop

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +* **Going a step further: **If you want to take things a step further and introduce an animation, sound effect, or other prettiness factor, we would introduce it after `brick(x, y)`. Try adding `prin
Typo on the `**` makes this render incorrectly in the HTML. the last two `**`s should be next to the `:`, not the `If`

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +You can also add other types of roadblocks into the app to make it more difficult, which usually incites making the game more addictive:
"incites making the game" is awkward phrasing, you could probably just do "which makes the game"

2020-11-30 19:29 UTC, MatthewStanciu commented on workshops/pacman game/README.md
> +
Maybe here add something like "Congrats! You've just made your own Pacman game! 🎉"

2020-11-30 19:29 UTC, MatthewStanciu commented
As usual, closing for now, but feel free to reopen once you feel it's ready to be merged

2020-11-30 19:29 UTC, closed without merging

2020-11-30 20:19 UTC, YashKalbande commented
@MatthewStanciu i have completed all requested changes. Please review my new work shop