VR Worlds (Workshop Bounty)
hackclub/hackclub pull request #1447
Opened 2020-11-18 19:33 UTC by wollygfx

2020-11-18 23:43 UTC, wollygfx commented
Demo video: https://hackclub.slack.com/files/U015HRC40H4/F01F2DD3YBC/workshop.mov

2020-12-02 04:49 UTC, sampoder requested changes
This is so cool @wollygfx!!!!!!!

It's simple but you make something EPIC. I love it! 

Just a tiny few things that need fixing before approving:

- Could you check that all the assets are available? Some are missing.
- Could you clean up the Markdown a bit, not the biggest deal tho.
- Could you use a langagues link for repl.it, makes it easier for club members
- Remember to use html throughout for markdown syntax highlighting
- For the expansion demos could you add the source code
- Check the grammar, just general check ups nothing big. Grammarly could probs catch them all

I think this is so so close and I'm so so excited! Gotta close this but soon soon I promise :)))

Looking forward,

Sam

2020-12-02 04:49 UTC, closed without merging

2020-12-03 00:36 UTC, wollygfx commented
Hey @sampoder 
Here's my current progress: 
- [x] Could you check that all the assets are available? Some are missing.
- [x] Could you clean up the Markdown a bit, not the biggest deal tho.
- [ ] Could you use a langagues link for repl.it, makes it easier for club members
- [ ] Remember to use html throughout for markdown syntax highlighting
- [ ] For the expansion demos could you add the source code
- [x] Check the grammar, just general check ups nothing big. Grammarly could probs catch them all
There are some things that I don't understand yet though:

1. What do you mean by this?

> Could you use a langagues link for repl.it, makes it easier for club members

2. Also, this:

> Remember to use html throughout for markdown syntax highlighting

and finally, the demo links are made by other people, i might not be able to find their source codes... Is okay if i just leave it like that?

2020-12-03 00:39 UTC, sampoder commented
1. I mean like using repl.it/languages/html as the link

2. i mean making your code blocks like:

````
\```html
html
\```
````

3. @MatthewStanciu thoughts?

2020-12-03 00:39 UTC, sampoder commented
ignore the black slashes

2020-12-03 00:44 UTC, wollygfx commented
@sampoder Wait but 
1. That link is already there
2. All the code blocks are already like that too

2020-12-03 00:50 UTC, sampoder commented on workshops/VR World/README.md
> +```js
not here ;)

2020-12-03 00:51 UTC, sampoder commented
Oh yep missed that, open up another PR and I'll review

2020-12-03 00:52 UTC, wollygfx commented on workshops/VR World/README.md
> +```js
the <script> tag?

2020-12-03 00:58 UTC, sampoder commented on workshops/VR World/README.md
> +```js
the ```js should be ```html

2020-12-03 00:58 UTC, sampoder commented on workshops/VR World/README.md
> +```js
omg \``` js should be \```html

2020-12-03 00:59 UTC, wollygfx commented on workshops/VR World/README.md
> +```js
Oh yeah, i'll change that