Chart js (Workshop Bounty)
hackclub/hackclub pull request #1453
Opened 2020-11-21 16:07 UTC by wollygfx

2020-12-02 07:42 UTC, sampoder commented on workshops/Chart Js/README.md
> +img: ''
```suggestion
img: 'https://cloud-g96wt9icu.vercel.app/0screen_recording_2020-11-19_at_4.38.37_pm.gif'
```

2020-12-02 07:43 UTC, sampoder commented on workshops/Chart Js/README.md
> +
```suggestion
```

2020-12-02 07:43 UTC, sampoder commented on workshops/Chart Js/README.md
> +
```suggestion

```

2020-12-02 10:18 UTC, sampoder requested changes
Hey!

Thanks for submission, this is a fairly well written workshop and has great potential. However, I think it still has a way to go. 

My main concern with this workshop is that the end product isn't satisfactory enough. Would it be possible for you to build on top of the stuff you learn in this workshop to build a more complex product?

Hope that makes sense,

Sam 🚀

2020-12-02 10:19 UTC, closed without merging

2020-12-03 03:15 UTC, wollygfx commented
Hey @sampoder! – Sorry, I feel kinda bad because I've been mentioning you a lot of times today, hope you don't mind 💯 

So, regarding to what you said: 

> My main concern with this workshop is that the end product isn't satisfactory enough. Would it be possible for you to build on top of the stuff you learn in this workshop to build a more complex product?

I totally agree and I have an idea to fix this:

> 💡 The idea: A chart generator in which, you just put your data in like some sort of inputs, then you choose what type of chart you want to generate, and finally it generates a chart that you can use.

I would love if you could give me your thoughts on this. 😄

2020-12-03 14:53 UTC, sampoder commented
sounds like a great plan!