Reddit Client using Flask
hackclub/hackclub pull request #1459
Opened 2020-11-23 22:04 UTC by KaiDevrim

2020-11-25 07:12 UTC, KaiDevrim commented
https://hackclub.slack.com/files/U012U7V3Y6A/F01B1PLUS0J/zoom_0.mp4

2020-12-02 11:48 UTC, sampoder commented on workshops/reddit_viewer/README.md
> +author: '@Kai'
```suggestion
author: '@KaiDevrim'   
```

2020-12-02 12:11 UTC, sampoder requested changes
Hey @KaiDevrim!

This feels super super close to being mergeable but just a couple of things

- First up, could you make it a bit clearer about the ID part of the `.env` part, students might be a bit confused what their ID is.

- Also, there are some places with really detailed description... but others that lack it. The main one being adding the POST route which doesn't have much explanation.

- Could you clean up the markdown a bit? Main things: syntax highlighting and images on a new line.

- Could you add 3 hacking examples at the bottom?

Once these changes get made, we can probably merge this workshop!! 

Thank you,

Sam :rocket:

2020-12-02 12:12 UTC, closed without merging

2020-12-06 07:49 UTC, KaiDevrim commented
@sampoder What do you mean by syntax highlighting? All my multiline python code is highlighted?

2020-12-06 08:07 UTC, KaiDevrim commented
sorry, i was using the wrong file lol! i see now