Drum Pad (Resubmission)
hackclub/hackclub pull request #1474
Opened 2020-11-30 17:33 UTC by emmanuel39hanks

Criteria:

> **Criteria:**
> 
> * [x]  Workshop that meets all of the "Good workshops" guidelines outlined above (View below)
> * [x]  1-2 minute video clip from your test club meeting showing what members built (View: https://slack-files.com/T0266FRGM-F01BGHMCSR0-d76af4939e)
> * [x]  All assets (images, PDFs, and any other binaries) must be hosted using the #cdn channel on the Hack Club Slack for posterity and to cut down on repository size
> * [x]  All workshops must be in English at native-level proficiency. Phrasing and grammar must be perfect.
> * [x]  You must be either a registered Hack Club leader or an active member of the Slack (I am a club leader, and I also count as an active member in the community, I hope)
> 
> **Good workshops guidelines:**
> 
> Help club members produce a compelling and real project in under 20 minutes
> 
> > This workshop can be completed in under 20 minutes, based on the test meeting. I would define this as a compelling project as it is something they can show off and it is very visual. It is a real project as they will be using HTML, CSS & jQuery to make a beatmaker/drum pad.
> 
> Are very easy to hack on for long periods of time after completion
> 
> > Yes, during the test meeting only people found it interesting and wanting to add more functionality like recording etc. And having future plans with the project.
> 
> Have instructive and compelling images, GIFs, and visuals
> 
> > It does have them.
> 
> Use repl.it or a similar service that allows members to begin coding with one click
> 
> > Yes.
> 
> Link unknown concepts to external sources.
> Yes, I have linked docs and unknown sources.
> > It relates CSS animation keyframing to video animation keyframing and relates CSS variables to how variables in other languages.
> 
> End with at least 3 demos of how the project can be expanded, with live links and code links for each demo.
> 
> > Yes, it has 3 cool advanced projects created by others with live links and code links.
> 
> Please let me know if I missed anything, and feel free to improve it.

2020-12-03 03:16 UTC, sampoder approved these changes
Congratulations @emmanuel39hanks! I believe this is ready to go!

2020-12-03 05:14 UTC, emmanuel39hanks commented
@sampoder Thanks❤

2020-12-08 06:03 UTC, sampoder requested changes
Hey @emmanuel39hanks,

The workshop team has taken another look at this workshop and I regret to inform you that my original reviewed missed a few things. I've annotated them here.

Furthermore, we consulted a leader and they shared the following feedback:

<img width="764" alt="Screen Shot 2020-11-30 at 12 15 01 PM" src="https://user-images.githubusercontent.com/39828164/101433979-81e92900-3945-11eb-8d65-3ae5f5f3bf28.png">

Please address this to support us.

Thanks,

Sam

2020-12-08 06:03 UTC, sampoder commented on workshops/drum_pad/README.md
> +```html
really weird spacing, remove the gaps

2020-12-08 06:03 UTC, sampoder commented on workshops/drum_pad/README.md
> +When you click on the buttons, we have no sound. We need to write our JavaScript code that will get us sound.
```suggestion
When you click on the buttons, we have no sound. We need to write some JavaScript code that will play sounds.
```

2020-12-08 06:03 UTC, sampoder commented on workshops/drum_pad/README.md
> +To explain what we did above, we created a function called `play()`, it receives a parameter, which is `link`. This is the link to the sound. We then create an audio object and pass `link` to the obj
```suggestion
Here we created a function called `play()`, it receives a parameter, which is `link`. This is the link to the sound. We then create an audio object and pass `link` to the object. Now we can just load the audio with the `load()` function and play it with the `play()` function. A function is a block of code designed to perform a particular task, it is executed when "something" invokes it (calls it).
```

2020-12-08 06:03 UTC, sampoder commented on workshops/drum_pad/README.md
> +Let's navigate to our `index.html` file first, so we want the sound to play when each pad is click, we will need a way to call our `play()`. We will use an HTML attribute called `onclick=""`, learn m
check grammar, this doesn't flow well

2020-12-08 06:03 UTC, sampoder commented on workshops/drum_pad/README.md
> +Now that you have finished building, you share your beautiful creation with other people! Remember, it's as easy as giving them your URL! Don't forget to share it with me on Slack @emmanuel39hanks.
```suggestion
Now that you have finished building, you can share your beautiful creation with other people! Remember, it's as easy as giving them your URL! Don't forget to share it with me on Slack @emmanuel39hanks.
```

2020-12-08 06:03 UTC, sampoder commented on workshops/drum_pad/README.md
> +To finish, here are some branches that build upon this project:
```suggestion
To finish, here are some examples of what can be built on top of this project:
```

2020-12-08 13:40 UTC, emmanuel39hanks commented
@sampoder, thanks for the suggestions.
I did as you asked, you can re-review.

2020-12-13 03:00 UTC, sampoder commented on workshops/drum_pad/README.md
> +  margin: 10px  0;
```suggestion
  margin: 10px 0;
```

2020-12-13 03:00 UTC, sampoder commented on workshops/drum_pad/README.md
> +  box-shadow: 0  8px  6px  -6px  black;
weird spacing

2020-12-13 03:02 UTC, sampoder commented on workshops/drum_pad/README.md
> +<div  class="pad">
```suggestion
<div class="pad">
```

2020-12-13 03:02 UTC, sampoder commented on workshops/drum_pad/README.md
> +<!-- nested child divs -->
```suggestion
  <!-- nested child divs -->
```

2020-12-13 03:08 UTC, sampoder commented on workshops/drum_pad/README.md
> +<!DOCTYPE html>
this is different to what you get if you do this in repl.it

2020-12-13 03:11 UTC, sampoder requested changes
hey @emmanuel39hanks!

it's so so so close I feel then end! my main thing is that the code you give doesn't take into account the default code repl.it provides. For example, script.js is already linked by default

otherwise, @MatthewStanciu thoughts?

thanks!

sam

2020-12-13 03:11 UTC, closed without merging