Color scheme generator(workshop bounty)
hackclub/hackclub pull request #1481
Opened 2020-12-02 05:19 UTC by giridhar7632

Follows all the guidelines and link for video: https://hackclub.slack.com/archives/C01A9V5LPD0/p1606886323046400

2020-12-02 14:07 UTC, faisalsayed10 approved these changes
Just 1 change and everything's perfect! woohoo, nice job!

2020-12-02 14:30 UTC, giridhar7632 commented on workshops/color_scheme_generator/README.md
> +In this workshop we are going to use [React Hooks](https://reactjs.org/docs/hooks-intro.html). We're building a colorful app - 'random-color scheme generator' using react. It looks something like thi
just did!

2020-12-02 15:25 UTC, sampoder commented on workshops/color_scheme_generator/README.md
> +If you are familiar with these, Let’s get going.
```suggestion
If you are familiar with these, let’s get going.
```

2020-12-02 15:34 UTC, sampoder requested changes
I trust in Fayd's technical review, so I haven't performed a full one. However I would very carefully check the grammar of the workshop.

Thanks! 🚀

2020-12-02 16:02 UTC, giridhar7632 commented
@sampoder I checked grammar 😁

2020-12-03 03:18 UTC, sampoder requested changes
Closing to clean up the list, feel free to resubmit when you feel it's ready.

2020-12-03 03:18 UTC, sampoder commented on workshops/color_scheme_generator/README.md
> +For setting up the project fork the repl [here](https://repl.it/@Giridharhackclu/color-scheme-generator-starter#README.md). The starter repl contains ['create-react-app'](https://github.com/facebook/
@giridhar7632 please review the phrasing very closely, here's an example of a grammar / phrasing mistake.

2020-12-03 03:19 UTC, closed without merging