Color scheme generator(Resubmission)
hackclub/hackclub pull request #1490
Opened 2020-12-03 05:56 UTC by giridhar7632

I fixed the suggested changes. I hope it will get merged now😁

2020-12-03 07:35 UTC, HariOm987 commented on workshops/color_scheme_generator/README.md
> +You should have  basic knowledge about both [React.js](https://reactjs.org) as well as some of the new [ES6](https://www.w3schools.com/Js/js_es6.asp) features in JavaScript.
Typo: Extra space between "have" and "basic".

2020-12-03 07:42 UTC, HariOm987 commented on workshops/color_scheme_generator/README.md
> +For writing code, we will be using [Repl.it](https://repl.it). Repl.it is a online code editor to code in many different languages without any installations.
a online ---> an online

2020-12-03 09:08 UTC, giridhar7632 commented on workshops/color_scheme_generator/README.md
> +For writing code, we will be using [Repl.it](https://repl.it). Repl.it is a online code editor to code in many different languages without any installations.
okay😅
Thnak you

2020-12-05 04:38 UTC, faisalsayed10 commented
I'll do a rereview soon.

2020-12-05 12:07 UTC, faisalsayed10 requested changes
Ah, I just did the re-review and feels like it needs more of some grammatically corrections. Can you please take a look into this a fix the required changes?

2020-12-05 12:07 UTC, faisalsayed10 commented on workshops/color_scheme_generator/README.md
> +Add a [prop](https://reactjs.org/docs/components-and-props.html#props-are-read-only) `colors`, an `array`, which we will get from other components.
```suggestion
Add a [prop](https://reactjs.org/docs/components-and-props.html#props-are-read-only) `colors` which will be an `array`, which we will get from other components. 
```

2020-12-05 12:07 UTC, faisalsayed10 commented on workshops/color_scheme_generator/README.md
> +The functional components can accept arbitrary inputs (called “props”) and return React elements describing what should appear on the screen.
```suggestion
The functional components can accept arbitrary inputs (called “`props`”) and return React elements describing what should appear on the screen.
```

2020-12-05 12:07 UTC, faisalsayed10 commented on workshops/color_scheme_generator/README.md
> +You can add as many `useState()` calls as you want, to create as many state variables as you want. Just make sure you call it in the [top level]https://reactjs.org/docs/hooks-rules.html#only-call-hoo
```suggestion
You can add as many `useState()` calls as you want, to create as many state variables as you want. Just make sure you call it in the [top level](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) of a component (not in an `if` statement or in any other block). 
```

2020-12-05 12:07 UTC, faisalsayed10 commented on workshops/color_scheme_generator/README.md
> +You can add as many `useState()` calls as you want, to create as many state variables as you want. Just make sure you call it in the [top level]https://reactjs.org/docs/hooks-rules.html#only-call-hoo
link wasnt properly formatted

2020-12-05 12:07 UTC, faisalsayed10 commented on workshops/color_scheme_generator/README.md
> +Now create two variables `count` and `colors` array using `useState`.
```suggestion
Now create two states `count` and `colors` using `useState`. 
```

2020-12-05 12:07 UTC, faisalsayed10 commented on workshops/color_scheme_generator/README.md
> +const baseColor = randomColor().slice(1)
This is not clear about where this line of code should come

2020-12-05 12:19 UTC, giridhar7632 commented on workshops/color_scheme_generator/README.md
> +> **Note:** Hooks don’t work inside classes. But you can use them instead of writing classes.
Actually I took that directly from official documentation😅
I changed it now.

2020-12-05 12:26 UTC, giridhar7632 commented
I made changes as suggested😊

2020-12-05 13:44 UTC, faisalsayed10 approved these changes

2021-01-18 20:02 UTC, MatthewStanciu commented
Sorry for the delay. Well done!

2021-01-18 20:02 UTC, merged