Added Shapes Drawing Program (Workshop Bounty Resubmission #1)
hackclub/hackclub pull request #1495
Opened 2020-12-04 00:46 UTC by JakeGerber

Previous: #1446

I added keyboard support to replace middle and right mouse buttons for people with Macbooks. to have an easier time. I also went and fixed parts of my program based on suggestions. Only suggestion I did not understand was the "Could you use Markdown formatting?" suggestion because I'm pretty sure I already am?

2020-12-13 03:16 UTC, sampoder approved these changes

2020-12-23 12:24 UTC, sampoder requested changes
I reconsidered this workshop a bit, so to save Matthew I review I'd recommend checking out my other reviews about formatting.

2020-12-23 21:15 UTC, JakeGerber commented
> I reconsidered this workshop a bit, so to save Matthew I review I'd recommend checking out my other reviews about formatting.

Yeah that's all good. I'm going to get to all my reviewing after the 31st

2021-01-04 18:39 UTC, sampoder commented
Closing for now. Given this loads of time for changes. Putting it in the resubmission section on #1597

2021-01-04 18:39 UTC, closed without merging