Micro bit flappy bird
hackclub/hackclub pull request #1499
Opened 2020-12-04 16:37 UTC by giridhar7632

Follows all the guidelines and video for demo: [https://hackclub.slack.com/archives/C01A9V5LPD0/p1607099838047500](https://hackclub.slack.com/archives/C01A9V5LPD0/p1607099838047500)

2020-12-11 05:18 UTC, faisalsayed10 requested changes
Hello giridhar!
I just reviewed your workshop and its great!
Few things that needs attention are:
- At some places there are code chunks which are not properly explained which may lead to confusions. (try to explain every single function, method etc)

- I also suggest you to add appropriate and descriptive titles to each sections instead of naming them as "Step 1" "Step 2" etc.

- The prerequisite for this workshop is a bit inappropriate as we use TypeScript. So the person doing the workshop should have quite a good experience in JavaScript. A person with "Extremely Basic Knwoledge" won't be able to understand TypeScript.

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Let's create some randomly generated obstacles for the bird to crash💥
```suggestion
Let's create some randomly generated obstacles for the bird to crash 💥.
```

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Let's create some randomly generated obstacles for the bird to crash💥
please try to keep a space between the words and emojis so that it doesn't feel cluttered

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Using the `for` loop, iterate from 0 to 4. For every coordinate not equal to `emptyObstacleY` create and add obstacle sprites to the end of the obstacles array using the `push()` method.
```suggestion
Using the `for` loop, iterate from 0 to 4. For every coordinate not equal to `emptyObstacleY`, create and add obstacle sprites to the end of the obstacles array using the `push()` method.
```

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Now with every micro:bit restart you should see different autogenerated vertical obstacles.
```suggestion
Now with every micro:bit restart you should see different automatically generated vertical obstacles.
```

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Before continuing, make sure that obstacles are generated randomly and that the bird is moving up and down.
also add a statement similar to "if it doesn't work as expected, try to cross check your code"

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Let's make the obstacles move towards the bird. We have to make them move forever. The code inside `basic.forever()` keep running in the background.
check with the 3rd sentence, its a bit off.

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +        obstacles.removeAt(0).delete()
add an explanation for what the `removeAt(0)` is doing.

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +    for (let index = 0; index <= 4; index++) {
we don't know what's happening here and we might get confused. try to add a small code explanation here

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Let's create some spaces between generated obstacles. Create a new variable `ticks` to count how many iterations the forever loop has done and execute obstacle creation only `if` ticks is divisible b
confusing statement, why only divisible by `3`?

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Right now nothing happens when the bird is hit by an obstacle. We should end the game when the bird crashes into an obstacle. The built-in function `gameover()` ends the game and show some cool anima
```suggestion
Right now nothing happens when the bird is hit by an obstacle. We should end the game when the bird crashes into an obstacle. The built-in function `gameover()` ends the game and shows some cool animations. 
```

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +To do this, we have to iterate over the `obstacles` array and checking if any `obstacle` sprite coordinate equals the `bird` coordinate. Then we call `gameover()` function.
```suggestion
To do this, we have to iterate over the `obstacles` array and check if any `obstacle` sprite's coordinate is the same as the `bird`'s coordinate. If this condition turns out to be true, we call the `gameover()` function.
```

2020-12-11 05:18 UTC, faisalsayed10 commented on workshops/micro_bit_flappy_bird/README.md
> +Our Final will be:
```suggestion
Our final code should look something like this:
```

2020-12-11 09:39 UTC, giridhar7632 commented on workshops/micro_bit_flappy_bird/README.md
> +A micro:bit can only do what you tell it to do. You can use different programming languages to write programs like [Makecode](https://makecode.microbit.org/), which you can use to code in code blocks
done😅

2020-12-11 09:40 UTC, giridhar7632 commented on workshops/micro_bit_flappy_bird/README.md
> +Create a new LED sprite pointing to the right. A sprite is like a little LED creature you can tell what to do.
🙄

2020-12-13 10:25 UTC, giridhar7632 commented
@faisalsayed10  I edited the file as suggested

2020-12-13 11:05 UTC, faisalsayed10 approved these changes
Great!

2021-01-13 22:52 UTC, MatthewStanciu commented
Wow, well done!

2021-01-13 22:52 UTC, merged