Scalable Snowman Workshop (Workshop Bounty Resubmission #1)
hackclub/hackclub pull request #1501
Opened 2020-12-05 08:16 UTC by JakeGerber

I added left and right movement for the snowmen. Turtle does not seem to have any key down function (which is really annoying) so you have to keep pressing the keys.

2020-12-05 10:09 UTC, JakeGerber commented
Previous: #1466

2020-12-13 03:37 UTC, faisalsayed10 requested changes
Hey!
I just reviewed your workshop, we are very close to merge it but it needs some very few improvements.
- There is a lack of explanation overall. Please try to add more explanation to each and every code blocks.

- I recommend you to use the markdown syntax for images as you have used `<img src="">`

Yeah, that's it!

2020-12-13 03:37 UTC, faisalsayed10 commented on workshops/scalable_snowman_workshop/README.md
> +- We are setting our direction to down (turtle.setheading(270)) and going to the top of the first body part.
```suggestion
- We are setting our direction to down (`turtle.setheading(270)`) and going to the top of the first body part.
```

2020-12-13 03:37 UTC, faisalsayed10 commented on workshops/scalable_snowman_workshop/README.md
> +- We are setting our direction to down (turtle.setheading(270)) and going to the top of the first body part.
it shud be highlighted as a code.

2020-12-23 10:34 UTC, closed without merging