Python snake
hackclub/hackclub pull request #1515
Opened 2020-12-12 22:56 UTC by kyryloren

Followed all the workshop guidelines.

The club meeting showcase video: https://hackclub.slack.com/archives/C01A9V5LPD0/p1606605399044200

2020-12-16 07:11 UTC, faisalsayed10 requested changes
Hey! Awesome workshop! Just a few things which I noticed:

- Some functions from the curses library are a bit confusing, can u please explain each of them a bit more?

- This workshop lacks images and gifs, so at a point, the reader might just be looking at a wall of text and may get bored, I suggest you to add some gifs and images such as "this is what our preview should look like after we write this code", "this is how the snake looks like" "this is what it will look like when the game gets over"

2020-12-16 07:11 UTC, faisalsayed10 commented on workshops/python_snake/README.md
> +Today, we will be using `random` and `curses`. These should be at the top of the python file. These libraries are just python code that someone wrote.
```suggestion
Today, we will be using the `random` and `curses` libraries. These should be imported at the top of the python file. These libraries are just python code that someone else wrote for us to use.
```

2020-12-16 07:11 UTC, faisalsayed10 commented on workshops/python_snake/README.md
> +Think of the snake in blocks. The first block is the head. The head is at the initial `snk_x` and `snk_y` positions. This means that the the next body part has to be at 1 less X position than the hea
```suggestion
Think of the snake as a group of blocks. The first block is the head. The head is at the initial `snk_x` and `snk_y` positions. This means that the the next body part has to be at 1 less X position than the head. The next body part is 2 less X from the head. The next 3 and so on. Each list item in the `snake` list is an initial body part position.
```

2020-12-16 07:11 UTC, faisalsayed10 commented on workshops/python_snake/README.md
> +![Snake game demo in repl.it](https://cloud-h8v6zt88z.vercel.app/0snakereplit.gif)
We need to have the source code link and the final product link here

2020-12-23 11:29 UTC, faisalsayed10 commented
Alright, I'll do a rereview tonight!

2020-12-23 15:14 UTC, faisalsayed10 commented
alright looks good woohoo! :tada:

2020-12-23 15:14 UTC, faisalsayed10 approved these changes

2020-12-24 00:42 UTC, sampoder requested changes
This is sick! Haven't really reviewed it but did a quick demo and was wondering if we could make the error message more user friendly: 

<img width="593" alt="Screenshot 2020-12-24 at 8 41 38 AM" src="https://user-images.githubusercontent.com/39828164/103046617-d89c6700-45c3-11eb-9993-0abb50470b23.png">

2020-12-24 21:16 UTC, kyryloren commented
> This is sick! Haven't really reviewed it but did a quick demo and was wondering if we could make the error message more user friendly:
> 
> <img alt="Screenshot 2020-12-24 at 8 41 38 AM" width="593" src="https://user-images.githubusercontent.com/39828164/103046617-d89c6700-45c3-11eb-9993-0abb50470b23.png">

The program is supposed to be more of a quick and lightweight solution for a game in python. But yeah I can add it.

2021-01-13 23:56 UTC, MatthewStanciu commented
Wow! This is fantastic! Well done 🎉

2021-01-13 23:56 UTC, merged