Readme.md
hackclub/hackclub pull request #1535
Opened 2020-12-24 06:42 UTC by shivesh01

```in-review```
#1531 
I have made changes suggested by @sampoder 
Thanks for your suggestion

2020-12-25 10:22 UTC, sampoder requested changes
Hey! Thanks for submitting another version!

My main concern with this workshop is that it isn't flowing well, and sounds too tutorial and not like a project.

Alongside that the phrasing still needs work on and some grammar errors. I've done my best to point them out below.

Thanks!

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +description: 'Data visualization with Sea born'
Hmm could we make this sound more professional?

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +name: 'Make your own Heat map'
```suggestion
name: 'Make Your Own Heat Map'
```

standard capitalisation

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +We use data everywhere. Your smartphone for instance, or the satellite navigation system in your car; maybe the car itself, what not?
```suggestion
We use data everywhere. Your smartphone for instance, and the satellite navigation system in your car are a couple of examples.
```

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +[Click here to see working HEATMAP DEMO on repl](https://repl.it/@ShiveshSingh/Heatmap#main.py)
```suggestion
[Click here to see a working demo of today's project](https://repl.it/@ShiveshSingh/Heatmap#main.py)
```

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +> One step at a time is all it takes to get you there.
```suggestion
```

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +# Index
let's remove this, not much point imo

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +In this workshop, you will be using the python language and its libraries to create a stunning heatmap from scratch. Even if you don't know the python language no worries this tutorial will guide you
Capitalise Python

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +In this workshop, you will be using the python language and its libraries to create a stunning heatmap from scratch. Even if you don't know the python language no worries this tutorial will guide you
Punctuation at the end is also wrong

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +The heat maps are graphical representation of data where values are represented by shades of color. Heat maps make it easy to visualize complex data and understand it at a glance:
```suggestion
The heat maps are graphical representation of data where values are represented by shades of color. Heat maps make it easy to visualize complex data and understand it at a glance.
```

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +Even you can visualize the data, your data too!
```suggestion
```

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +You just need to set up an account on repl. you can run this program on your Python idle too. Idle like Pycharm, Atom, Jupyter notebook and Visual studio e.t.c. Some basic knowledge is required for t
Capitals at the start of every sentence, also awkward phrasing here

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +### Setting up an account on repl
Combine these two titles

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +[Repl website](https://repl.it/signup) and create a repl
make this flow better

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +
make this section flow better

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +*A Violin Plot is used to visualize the distribution of the data and its probability density.  Show the distribution shape of the data.*
awkward phrasing

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +Frankly share with everyone🤗✌️🥳👏🏅🌇🎊**
frankly is a weird word to use here

2020-12-25 10:22 UTC, sampoder commented on workshops/HEATMAP/README.md
> +# Keep Hacking!
need three demos and code links

2020-12-25 10:22 UTC, closed without merging

2020-12-26 14:25 UTC, shivesh01 commented
#1535 
Hey @sampoder, I have made some changes. Hope you like it. 
Duplicate of #