feat: add rust text game workshop
hackclub/hackclub pull request #1561
Opened 2020-12-28 12:41 UTC by cfanoulis

- [x] You must be a club leader or an active community member in order to submit a workshop => I am [Hackropolis's](https://hackropolis.club) leader
- [x] Your workshop must produce a compelling, specific, real project, using real code. It should not be a tutorial for a language or service. It should also not be a series of small projects with no clear ending or final product. => This workshop produces a text-based game, similar to Zork
- [ ] Your workshop must be able to be completed in around 20 minutes, but it should be very easy for people to make big changes to it. => We haven't had the demo meeting yet, so we cannot be sure of the time. It is however, highly hackable
- [x] At the end of your workshop, you must include links to at least 3 demos clearly showing the initial project being changed in big ways. These demos should serve as examples for how hackable your workshop is. Each demo should include a link to the project and a link to the source code. => Only include 1, but we have had clearance from Sam.
- [x] Your workshop must involve code, and not require desktop software or hardware, since not all clubs will have those resources. => Workshop includes instruction for both repl.it & local hacking
- [x] At the beginning of your workshop, you must include the link to the final demo and the final code. => Included, as well as [for your consideration](https://repl.it/@hackropolis/stickerquest)
- [x] Your workshop must be in English at native-level proficiency. Phrasing and grammar must be perfect.
- [x] By default, all workshops should be written in Markdown or another format that can be easily be added to the Workshops page. Workshops submitted in a different format are also encouraged, but the format must be approved by matthew first => Workshop has been submitted in Markdown
- [x] Each step in your workshop should be very clearly explained and should continually give context for where the user is in the workshop. => We have done so to the best of our capabilities
- [x] Your workshop must not be the same or too similar to any existing workshop. Make sure to check on this before you start writing your workshop—if your workshop is too similar to an existing one, it won't be able to be merged at all! => The only other Rust workshop currently is about a Discord bot.
- [x] Every piece of media (image, GIF, video, etc.) you include in your workshop should include alt text that clearly describes what's in the piece of media => We have done so.

Source Code: https://github.com/hackropolis/stickerquest
Demo Meeting: [not yet executed]

2020-12-28 12:43 UTC, sampoder commented
🎉 HEY!!! Yay!

2020-12-28 14:12 UTC, panos commented
Hey, can you rename the commit to 

```
Added Text Adventure Game in Rust

Co-authored-by: [full name from my github profile] <email from my github profile>
````

Thanks!

2020-12-28 14:12 UTC, panos commented
Also, we weren't particularly sure how to add more than one author, so we just added the tag twice as adding two usernames in the same tag would probably turn things, considering that `@panos -> https://github.com/panos`.

2020-12-28 14:35 UTC, sampoder commented on workshops/rust_text_game/README.md
> +author: "@fanoulis"
```suggestion
```

2020-12-28 14:35 UTC, sampoder commented on workshops/rust_text_game/README.md
> +author: "@panos"
```suggestion
author: "@panos, @fanoulis"
```

2020-12-28 15:11 UTC, sampoder commented on workshops/rust_text_game/README.md
> +
Note to add part about importing standard library

2020-12-28 15:45 UTC, sampoder requested changes
Hey friends!

Thank you for submitting a workshop and for having me on the demo tonight!

I think this workshop is basically there, and there are just two thoughts I have:

- Let's focus just on the process when using repl.it.. the duo set up made it a bit confusing for me.
- I also think that the workshop needs to provide the reader of a better launchpad to making their game from the workshop. I think there needs to be some part of the workshop which tells you how to turn this program into an adventure game. I recognise we've kinda moved away from adventure games, but I feel like at the end you should finish with at least some sort of game. Not sure if that makes sense or not.

Thanks,

Sam 🚀

2020-12-28 15:58 UTC, panos approved these changes

2020-12-28 16:20 UTC, panos commented
I started writing an example in the end of the guide, is that starting to look a bit better? @sampoder

2020-12-29 03:03 UTC, sampoder commented
It's much better, but maybe a bit more writing about it though. Thanks @panos

2020-12-29 03:07 UTC, sampoder commented on workshops/rust_text_game/README.md
> +Here's a summary of how the code should look like:
This could introduce it as like handy the project to you... like a DIY thing.. apply your knowledge to make a full thing

2020-12-29 10:30 UTC, panos commented
> It's much better, but maybe a bit more writing about it though. Thanks @panos

Alright, we'll finish the example game and add a few additional notes, such as how/why we're calling the functions instead etc.

Are there any other details we may have missed and to be ironed out?

2020-12-29 13:45 UTC, sampoder commented
Nope, otherwise I think it's good 🙌

2020-12-29 13:45 UTC, sampoder commented
Going to close this for now as you working on the resubmission, looking forward to it!

2020-12-29 13:45 UTC, closed without merging

2020-12-29 16:35 UTC, panos commented
> Going to close this for now as you working on the resubmission, looking forward to it!

Is it a problem if we re-open this until we finish it under the same pull request for the sake of posterity?

2020-12-29 16:35 UTC, panos commented
> > Going to close this for now as you working on the resubmission, looking forward to it!
> 
> Is it a problem if we re-open this until we finish it under the same pull request for the sake of posterity as soon as we're done? It's just that I don't see a real reason to open a new pull request when we'll keep using the same branch instead.

2021-01-01 03:42 UTC, sampoder commented
Could you open it in a new PR, I know it's not standard but that's how we're handling things.