Website mockup generator - PR #2
hackclub/hackclub pull request #1578
Opened 2020-12-30 15:49 UTC by hackyguru

Heya! I've redesigned the site to make it look more attractive. I tried to address all your suggestions and I hope I am ready for a review. Thanks!

2020-12-30 15:51 UTC, sampoder reviewed
Not a full review, but the website does look more attractive! Nice work!

2021-01-04 07:42 UTC, faisalsayed10 requested changes
Hey, nice work since the last review! Here's my review again:

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +In order to place a text input field to get the website from the URL, use the following line to create a text input with a placeholder 'Enter the website' and provide id to the input as 'websiteAddre
```suggestion
In order to place a text input field to get the website from the URL, use the following line to create a text input with a `placeholder` 'Enter the website' and provide `id` to the input as `websiteAddress`.

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +In order to place a text input field to get the website from the URL, use the following line to create a text input with a placeholder 'Enter the website' and provide id to the input as 'websiteAddre
code related words should get a special formatting of code

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +We need two buttons to generate the mockup and to download respectively. Use the `<button>` tag twice to place the buttons. Provide the button label in between the `<button></button>` tags. Provide t
```suggestion
We need two buttons to generate the mockup and to download respectively. Use the `<button>` tag twice to place the buttons. Provide the button label in between the `<button></button>` tags. Provide the `id` as `submitButton` for the 'Generate mockup' button and `Download` for 'Download' button.

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +We will be using an `<img>` tag to display the generated mockup image. Provide the id as `resultImg`.
```suggestion
We will be using an `<img>` tag to display the generated mockup image. Provide the `id` as `resultImg`.

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Now, let us customize the body style. Change the body background using `background-color: red;`. Change the body text color into white using `color : white;`. To make the website look better, let us
```suggestion
Now, let us customize the `<body>` tag. we will change the background color to and the text color to white. To make the website look better, let us align our items to center using `align-items` and `justify-content`:
```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Now, let us customize the body style. Change the body background using `background-color: red;`. Change the body text color into white using `color : white;`. To make the website look better, let us
this way, it will look better so that the person first reads what we will be doing and then actually implements it

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +    <input type="text" id="websiteAdress" placeholder='Enter the website'>
typo "websiteAdress"

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +    <button type="submit" id="submitBtn" onclick='generateMockup();'>Generate Mockup</button>
this semicolon can be removed, it will look better and it still works!

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +#websiteAdress {
typo

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +```
this might be tricky for beginners, please explain what's happening

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +}
lacking explanation

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Finally, create a CSS class called `cont` and provide the follow properties. We have used the `cont` class in the HTML.
```suggestion
Finally, create a CSS class called `cont` and provide the following properties. We have used the `cont` class in the HTML.

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Finally, create a CSS class called `cont` and provide the follow properties. We have used the `cont` class in the HTML.
please specify "where" at "we have used the cont class in HTML"

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Finally, create a CSS class called `cont` and provide the follow properties. We have used the `cont` class in the HTML.
i mean, which element do we use the cont class

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +#websiteAdress {
typo

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +- Allow users to download the image by pressing 'Download' button
fullstops missing

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +#### Getting the elements from HTML in JS by their Id
```suggestion
#### Getting the elements from HTML in JavaScript by their `id`

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Firstly, we will be getting the elements from HTML into JavaSript by using their id using the following code :
```suggestion
Firstly, we will be getting the elements from HTML into JavaSript by using their `id` using the following code :

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +#### Defining the generateMockup() function
```suggestion
#### Defining the `generateMockup()` function

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +In order to generate the mockups, we will be defining the generateMockup() function which is called when the 'Generate Mockup' button is pressed. Create a function called generateMockup() using:
```suggestion
In order to generate the mockups, we will be defining the `generateMockup()` function which is called when the 'Generate Mockup' button is pressed.

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +Now, assign the values of `websiteAddress` amd `color` to the value from the text input field using :
```suggestion
Now, assign the values of `websiteAddress` and `color` to the value from the text input field using :

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +  resultImg.src = mockup;
this directly appeared in the final code

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +To allow users download the mockup image by pressing the download button, include the following code inside the `generateMockup()` function.
```suggestion
To allow users to download the mockup image by pressing the download button, include the following code inside the `generateMockup()` function.

```

2021-01-04 07:42 UTC, faisalsayed10 commented on workshops/website_mockup_generator/README.md
> +- Add more window frames
3 examples links are required

2021-01-04 07:42 UTC, closed without merging