JsonDB Workshop (Workshop Bounty)
hackclub/hackclub pull request #1594
Opened 2021-01-01 02:20 UTC by safinsingh

Video: https://hackclub.slack.com/archives/C01A9V5LPD0/p1609467411063700

2021-01-04 07:52 UTC, faisalsayed10 requested changes
Awesome workshop!

2021-01-04 07:52 UTC, faisalsayed10 commented on workshops/json_db/README.md
> +In the screenshot above, I've copied in the URL of my REPL (in the format: https://<PROJECT_NAME>.<USERNAME>.repl.co) and set the request type to GET. Finally, hit `Send`! You should get a plain resp
```suggestion
In the screenshot above, I've copied in the URL of my REPL (in the format: `https://<PROJECT_NAME>.<USERNAME>.repl.co`) and set the request type to GET. Finally, hit `Send`! You should get a plain response like so:
```

2021-01-04 07:52 UTC, faisalsayed10 commented on workshops/json_db/README.md
> +In the screenshot above, I've copied in the URL of my REPL (in the format: https://<PROJECT_NAME>.<USERNAME>.repl.co) and set the request type to GET. Finally, hit `Send`! You should get a plain resp
without the code formatting, it was acting weird as the <USERNAME> part was not visible

2021-01-04 07:52 UTC, faisalsayed10 commented on workshops/json_db/README.md
> +Q: What's middleware?
```suggestion
Q: What's middleware?  
```

2021-01-04 07:52 UTC, faisalsayed10 commented on workshops/json_db/README.md
> +Q: What's middleware?
we need double space to shift it on the new line

2021-01-04 07:52 UTC, faisalsayed10 commented on workshops/json_db/README.md
> +Q: What's middleware?
same for all these

2021-01-04 08:54 UTC, faisalsayed10 approved these changes

2021-01-04 16:03 UTC, safinsingh commented
@faisalsayed10, thanks for your suggestions! I've updated the workshop accordingly.

2021-01-15 19:08 UTC, MatthewStanciu commented
Wow, well done!

2021-01-15 19:09 UTC, merged