Javascript Typing Test (workshop)
hackclub/hackclub pull request #1595
Opened 2021-01-01 02:23 UTC by GurshanBrar

Hello there! This is my second pull request, so obviously I have to thank you for the dedication you put into reviewing this for me.

The link to the mock meeting:
https://hackclub.slack.com/archives/C01A9V5LPD0/p1609467151063400

We create a small little typing speed test in this workshop. It tells you the WPM, accuracy, and time.

2021-01-01 02:53 UTC, giridhar7632 commented on workshops/javascript_typing_test/README.md
> +		<div class="text-container" id="text-container"></div>
take care of indentation

2021-01-01 03:13 UTC, giridhar7632 requested changes
Hey! great work 😀
check the grammar and phrasing properly again

2021-01-01 03:13 UTC, giridhar7632 commented on workshops/javascript_typing_test/README.md
> +If you have any questions, you can ping me on slack(@Gurshan) or [my github](https://github.com/gurshanbrar).
You can add the link to your hackclub slack profile

2021-01-01 03:13 UTC, giridhar7632 commented on workshops/javascript_typing_test/README.md
> +### First up, the project
Double check the grammar and phrasing

2021-01-01 03:13 UTC, giridhar7632 commented on workshops/javascript_typing_test/README.md
> +1. It saves your code in the cloud
check the ordered lists
they will not render properly on the site

2021-01-01 22:42 UTC, GurshanBrar commented
### Hi! These changes were requested and committed: 

- Fix grammar and phrasing throughout
- Indent block of code
- Render ordered lists properly
- Add link to slack profile
- Use `<details>` tag

#### Also, thank you for the single backtick suggestion. I will keep that in mind for the future!

2021-01-05 02:57 UTC, sampoder commented on workshops/javascript_typing_test/README.md
> +If you have any questions, you can ping me on [my slack profile](hackclub.slack.com/team/U0198EM6ZA7) or [my github](https://github.com/gurshanbrar).
```suggestion
If you have any questions, you can message me on [Slack](hackclub.slack.com/team/U0198EM6ZA7) or [visit my GitHub](https://github.com/gurshanbrar). 
```

2021-01-05 03:06 UTC, sampoder requested changes
Hey!! This looks super close, just one thing: could we add more explanation of the JS code starting from `Section 2`? Thanks!

2021-01-05 03:07 UTC, closed without merging