Digit Recognition Workshop
hackclub/hackclub pull request #1600
Opened 2021-01-01 05:04 UTC by rpalakkal

i'll do the recording sometime soon!

2021-01-07 03:43 UTC, faisalsayed10 requested changes
Hello! Just did a review of this workshop, I personally liked this workshop! Just one thing that need to done:

- I feel that this workshop is a bit complex one, so maybe add a prerequisites section before hopping into the workshop?

2021-01-07 03:43 UTC, faisalsayed10 commented on workshops/digit_recognition/KerasMNIST.md
> +    [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
can you please tell something about what this is? (like a one line description of this block)

2021-01-07 03:44 UTC, faisalsayed10 commented
Also, maybe rename the file to `README.md` because that's how all the workshops are structured.

2021-01-09 18:21 UTC, sampoder commented
Closing for now, excited for the resubmission 🚀

2021-01-09 18:21 UTC, closed without merging