Workshop On Hosting, Custom Domains and More
hackclub/hackclub pull request #1634
Opened 2021-01-11 11:47 UTC by aaryanporwal

Resubmission of : #1560

2021-01-14 12:03 UTC, sampoder requested changes
Hey Aaryan!

Thank you for submission, alongside my comments here are a couple of pointers.

- The grammar needs significant improvement. Read the workshop out slowly to yourself and fix up any issues that block the flow.
- This workshop probably needs to actually introduce the key terms in it's title and what they mean.
- This workshop needs to be more flexible to accommodate for the different situations clubs are in.

Thanks,

Sam 🚀

2021-01-14 12:03 UTC, sampoder commented on workshops/hosting-workshop/README.md
> +Other is that if you want to make your website Closed Source (that is don't want the source code to be open to public), you can simply make your GitHub repository private.
```suggestion
The other solution is to make your website closed source (if you don't want the source code to be public). To achieve this you can simply make your GitHub repository private.
```

2021-01-14 12:03 UTC, closed without merging

2021-01-24 10:07 UTC, aaryanporwal commented on workshops/hosting-workshop/README.md
> +2. Next, we need [GitHub's student developer pack](https://education.github.com/pack) for this Workshop so that we can take advantage of namecheap's free 1 year custom domain name, for this you can t
@sampoder When I wrote the workshop, it was up and running :(
Do you think, I should just remove it altogether?

2021-01-24 10:09 UTC, aaryanporwal commented on workshops/hosting-workshop/README.md
> +First, get a free one year custom domain from [Namecheap Education](https://nc.me) using your GitHub account.
Yeah, that's the beauty of SDP, you don't need credit card or anything for buying a domain from Namecheap!

2021-01-24 10:11 UTC, aaryanporwal commented on workshops/hosting-workshop/README.md
> +First, get a free one year custom domain from [Namecheap Education](https://nc.me) using your GitHub account.
You can get a `.me` domain free for one year on namecheap!

2021-01-24 10:30 UTC, sampoder commented on workshops/hosting-workshop/README.md
> +2. Next, we need [GitHub's student developer pack](https://education.github.com/pack) for this Workshop so that we can take advantage of namecheap's free 1 year custom domain name, for this you can t
for now probably :/