Update CODE_OF_CONDUCT.md
hackclub/hackclub pull request #1704
Opened 2021-02-10 21:09 UTC by Hugoyhu

There are loopholes in the current- as "excessive", "non-beneficial" and "commercials".

The current stance of slack appears to be against any advertisement not permitted by HQ, my updated line is likely more sufficient.

2021-02-14 06:29 UTC, sampoder commented
cc: @hackclub/community-team & @hackclub/core

2021-02-14 06:30 UTC, sampoder commented on CODE_OF_CONDUCT.md
> +- Advertisement for events, companies, organizations, etc- unless specifically given permission by Staff, Community Team, or a Hack Club Community Game Designer.
```suggestion
- Advertisement for events, companies, organizations, etc- unless specifically given permission by Hack Club HQ.
```

2021-02-16 04:15 UTC, cjdenio commented
I think this looks good!

2021-03-19 13:35 UTC, juliegoat commented
It looks good to me too - makes sense! @zfogg

2021-03-25 18:49 UTC, zfogg commented
i am reviewing this thank you @Hugoyhu may corgis surround you for all of your days

2021-03-25 19:52 UTC, zfogg requested changes

2021-03-25 20:03 UTC, zfogg approved these changes
lgtm

2021-03-25 20:04 UTC, merged